# ======================================================= #
# -------------------- Basic Settings ------------------- #
# ======================================================= #

#Placeholders
# - "<player-name>" - player name
# - "<prefix>" - luckperms prefix

join-message: "<prefix> &a<player-name> has joined the party!"
blacklisted-entities:
  - PHANTOM

#Home groups, name of group followed by the permission node and the amount of homes this group gets
#The group name doesn't matter, just to help configurators identify the group in the config.
homes:
  default:
    permission: "elements.homes.3"
    count: 3

chat-filter:
  - "changeme"
  - "changeme2"

#These are the settings to change related to xray alerts
xray-alerts:
  diamond_ore:
    check-interval: 30
    required-amount: 15
  gold_ore:
    check-interval: 30
    required-amount: 20
  emerald_ore:
    check-interval: 30
    required-amount: 10

