# ======================================================= #
# -------------------- Basic Settings ------------------- #
# ======================================================= #

#Placeholders
# - "<player-name>" - player name
# - "<prefix>" - luckperms prefix

join-message: "<prefix> &a<player-name> has joined the party!"
blacklisted-entities:
  - PHANTOM

#Home groups, name of group followed by the permission node and the amount of homes this group gets
#The group name doesn't matter, just to help configurators identify the group in the config.
homes:
  default:
    permission: "elements.homes.3"
    count: 3

#These are message contents which will be blocked
chat-filter:
  - "ch_ngeme"
  - "changeme"


#These are the settings to change related to xray alerts
xray-alerts:
  diamond_ore:
    check-interval: 10
    required-amount: 15
  gold_ore:
    check-interval: 30
    required-amount: 20
  emerald_ore:
    check-interval: 30
    required-amount: 10

#This setting is used to determine whether tnt/creepers can break blocks
explosion-block-damage: false

# ======================================================= #
# ------------------- Spawner Settings ------------------ #
# ======================================================= #

spawners:

  #Put the exact entity name (in lowercase) and add the "cost" key, this is the cost in Exp Levels
  #Also add the "display-name" key, this will contain the name which is displayed in-game to players.
  spawner-types-shop:
    pig:
      cost: 30
      display-name: "&dPig"
    zombie:
      cost: 30
      display-name: "&aZombie"
    lightning:
      cost: 9999
      display-name: "&eLightning \u26A1"

