name: Elements
depend: [LuckPerms]
version: ${project.version}
main: me.ofearr.elements.Elements
api-version: 1.13
authors: [oFearr]
description: Fully equiped bukkit plugin to take care of most of your needs
commands:
  gms:
    description: Updates your gamemode to Survival!
    aliases:
      - gamemodes
  gmc:
    description: Updates your gamemode to Creative!
    aliases:
      - gamemodec
  gmsp:
    description: Updates your gamemode to Spectator!
    aliases:
      - gamemodesp
  gma:
    description: Updates your gamemode to Adventure!
    aliases:
      - gamemodea
  playerlist:
    description: Opens the player list GUI!
    aliases:
      - players
  sethome:
    description: Sets a home at your current location with the specified name.
  home:
    description: Sends you to the specified home.
  homes:
    description: Opens the homes GUI.
    aliases: [homelist]
  feed:
    description: Fully saturates your hunger bar.
  heal:
    description: Fully heals you.
  fly:
    description: Allows you to fly!
  togglealerts:
    description: Toggles xray alerts.
    aliases: [disablealerts, togglexray, togglexrayalerts, xrayalerts, alerts, monitor]
  togglechat:
    description: Toggles whether chat is enabled or not.
    aliases: [chatenable, chattoggle]
  givespawner:
    description: Gives the player x spawners of x type.
    aliases: [gs, spawnergive]
  vanish:
    description: Hides you from everyone who cannot use this command.
    aliases: [v, elementsvanish, ev, hideme]
  glow:
    description: Makes you glow!
  openinv:
    description: Opens the target player's inventory.
    aliases: [openinventory, invsee]
  broadcast:
    description: Sends the specified message to all online players.
    aliases: [bc, sendall]
  adminchat:
    description: Sends a message to all the admins.
    aliases: [ac, chatadmin]

permissions:
  elements.*:
    children:
      elements.gmc: true
      elements.gms: true
      elements.gmsp: true
      elements.gma: true
      elements.playerlist: true
      elements.homes.max: true
      elements.home: true
      elements.sethome: true
      elements.homelist: true
      elements.feed: true
      elements.heal: true
      elements.admin: true
      elements.xrayalerts: true
      elements.togglechat: true
      elements.givespawner: true
      elements.spawnerupgrades: true
      elements.vanish: true
      elements.glow: true
      elements.openinventory: true
      elements.broadcast: true
      elements.adminchat: true
